[package]
name = "blukey"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.12"
daemonize = "0.5"
clap = { version = "4.4", features = ["derive"] }
nix = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"