name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
      is_prerelease:
        description: 'Is this a prerelease?'
        required: true
        default: 'false'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Run build script
        run: ./build.sh && ls && pwd && ls /home/runner/work/blukey/blukey/release

      - name: Upload Release Assets and Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.event.inputs.release_name }}
          prerelease: ${{ github.event.inputs.is_prerelease }}
          title: ${{ github.event.inputs.release_name }}
          files: /home/runner/work/blukey/blukey/release/*
